import type { Metadata } from 'next';
import Navbar from '@/components/navbar';
import ScrollSmootherWrapper from '@/components/scrollSmootherWrapper';
import styles from '@/styles/layout.module.scss';
import '@/styles/base.scss';

export const metadata: Metadata = {
  title: 'lu.is',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Navbar />
        <ScrollSmootherWrapper>
          <main className={styles.overall}>
            <div className={styles.mainContainer}>{children}</div>
          </main>
        </ScrollSmootherWrapper>
      </body>
    </html>
  );
}
